/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ChatApi
import org.openapitools.client.models.CoreChat
import org.openapitools.client.models.CoreMessageInfo
import org.openapitools.client.models.CoreUserInfo
import org.openapitools.client.models.HandlerAddChat
import org.openapitools.client.models.HandlerAddMember
import org.openapitools.client.models.HandlerChatIdResponse
import org.openapitools.client.models.RespErrorResponse

class ChatApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChatApi
        //val apiInstance = ChatApi()

        // to test chatAddMembersPost
        should("test chatAddMembersPost") {
            // uncomment below to test chatAddMembersPost
            //val body : HandlerAddMember =  // HandlerAddMember | Список users_id
            //apiInstance.chatAddMembersPost(body)
        }

        // to test chatAllGet
        should("test chatAllGet") {
            // uncomment below to test chatAllGet
            //val result : kotlin.collections.List<CoreChat> = apiInstance.chatAllGet()
            //result shouldBe ("TODO")
        }

        // to test chatIdDelete
        should("test chatIdDelete") {
            // uncomment below to test chatIdDelete
            //val id : kotlin.Int = 56 // kotlin.Int | ID чата
            //apiInstance.chatIdDelete(id)
        }

        // to test chatIdGet
        should("test chatIdGet") {
            // uncomment below to test chatIdGet
            //val id : kotlin.Int = 56 // kotlin.Int | ID чата
            //val result : CoreChat = apiInstance.chatIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test chatMembersIdGet
        should("test chatMembersIdGet") {
            // uncomment below to test chatMembersIdGet
            //val id : kotlin.Int = 56 // kotlin.Int | ID чата
            //val result : kotlin.collections.List<CoreUserInfo> = apiInstance.chatMembersIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test chatMessagesGet
        should("test chatMessagesGet") {
            // uncomment below to test chatMessagesGet
            //val chatId : kotlin.Int = 56 // kotlin.Int | ID чата
            //val pageId : kotlin.Int = 56 // kotlin.Int | номер страницы
            //val result : kotlin.collections.List<CoreMessageInfo> = apiInstance.chatMessagesGet(chatId, pageId)
            //result shouldBe ("TODO")
        }

        // to test chatPost
        should("test chatPost") {
            // uncomment below to test chatPost
            //val body : HandlerAddChat =  // HandlerAddChat | Данные для создания чата
            //val result : HandlerChatIdResponse = apiInstance.chatPost(body)
            //result shouldBe ("TODO")
        }

    }
}
