/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.ContactApi
import org.openapitools.client.models.CoreUserInfo
import org.openapitools.client.models.HandlerAddContact
import org.openapitools.client.models.RespErrorResponse

class ContactApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ContactApi
        //val apiInstance = ContactApi()

        // to test contactAllGet
        should("test contactAllGet") {
            // uncomment below to test contactAllGet
            //val result : kotlin.collections.List<CoreUserInfo> = apiInstance.contactAllGet()
            //result shouldBe ("TODO")
        }

        // to test contactIdDelete
        should("test contactIdDelete") {
            // uncomment below to test contactIdDelete
            //val id : kotlin.Int = 56 // kotlin.Int | ID контакта
            //apiInstance.contactIdDelete(id)
        }

        // to test contactIdGet
        should("test contactIdGet") {
            // uncomment below to test contactIdGet
            //val id : kotlin.Int = 56 // kotlin.Int | ID контакта
            //val result : CoreUserInfo = apiInstance.contactIdGet(id)
            //result shouldBe ("TODO")
        }

        // to test contactPost
        should("test contactPost") {
            // uncomment below to test contactPost
            //val body : HandlerAddContact =  // HandlerAddContact | Логин контакта
            //apiInstance.contactPost(body)
        }

    }
}
