/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.MessengerApi
import org.openapitools.client.models.RespErrorResponse

class MessengerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MessengerApi
        //val apiInstance = MessengerApi()

        // to test messengerConnectGet
        should("test messengerConnectGet") {
            // uncomment below to test messengerConnectGet
            //val chatId : kotlin.Int = 56 // kotlin.Int | ID чата подключения
            //apiInstance.messengerConnectGet(chatId)
        }

    }
}
