/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.UserApi
import org.openapitools.client.models.HandlerRefresh
import org.openapitools.client.models.HandlerRefreshRes
import org.openapitools.client.models.HandlerSign
import org.openapitools.client.models.HandlerUserName
import org.openapitools.client.models.RespErrorResponse

class UserApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserApi
        //val apiInstance = UserApi()

        // to test userRefreshPost
        should("test userRefreshPost") {
            // uncomment below to test userRefreshPost
            //val body : HandlerRefresh =  // HandlerRefresh | Данные для регистрации
            //val result : HandlerRefreshRes = apiInstance.userRefreshPost(body)
            //result shouldBe ("TODO")
        }

        // to test userSetUsernamePost
        should("test userSetUsernamePost") {
            // uncomment below to test userSetUsernamePost
            //val body : HandlerUserName =  // HandlerUserName | Данные для установки имя пользователя
            //apiInstance.userSetUsernamePost(body)
        }

        // to test userSignInPost
        should("test userSignInPost") {
            // uncomment below to test userSignInPost
            //val body : HandlerSign =  // HandlerSign | Данные для регистрации
            //apiInstance.userSignInPost(body)
        }

        // to test userSignUpPost
        should("test userSignUpPost") {
            // uncomment below to test userSignUpPost
            //val body : HandlerSign =  // HandlerSign | Данные для регистрации
            //apiInstance.userSignUpPost(body)
        }

    }
}
