/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CoreMessageInfo

class CoreMessageInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CoreMessageInfo
        //val modelInstance = CoreMessageInfo()

        // to test the property `chatId`
        should("test chatId") {
            // uncomment below to test the property
            //modelInstance.chatId shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `senderId`
        should("test senderId") {
            // uncomment below to test the property
            //modelInstance.senderId shouldBe ("TODO")
        }

        // to test the property `sendingTime`
        should("test sendingTime") {
            // uncomment below to test the property
            //modelInstance.sendingTime shouldBe ("TODO")
        }

        // to test the property `text`
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

        // to test the property `userName`
        should("test userName") {
            // uncomment below to test the property
            //modelInstance.userName shouldBe ("TODO")
        }

    }
}
