/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CoreUserInfo

class CoreUserInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CoreUserInfo
        //val modelInstance = CoreUserInfo()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `login`
        should("test login") {
            // uncomment below to test the property
            //modelInstance.login shouldBe ("TODO")
        }

        // to test the property `userName`
        should("test userName") {
            // uncomment below to test the property
            //modelInstance.userName shouldBe ("TODO")
        }

    }
}
