/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HandlerAddContact

class HandlerAddContactTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HandlerAddContact
        //val modelInstance = HandlerAddContact()

        // to test the property `contactLogin`
        should("test contactLogin") {
            // uncomment below to test the property
            //modelInstance.contactLogin shouldBe ("TODO")
        }

    }
}
