/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HandlerAddMember

class HandlerAddMemberTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HandlerAddMember
        //val modelInstance = HandlerAddMember()

        // to test the property `chatId`
        should("test chatId") {
            // uncomment below to test the property
            //modelInstance.chatId shouldBe ("TODO")
        }

        // to test the property `membersIds`
        should("test membersIds") {
            // uncomment below to test the property
            //modelInstance.membersIds shouldBe ("TODO")
        }

    }
}
