/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HandlerAddChat

class HandlerAddChatTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HandlerAddChat
        //val modelInstance = HandlerAddChat()

        // to test the property `isDirect`
        should("test isDirect") {
            // uncomment below to test the property
            //modelInstance.isDirect shouldBe ("TODO")
        }

        // to test the property `membersIds`
        should("test membersIds") {
            // uncomment below to test the property
            //modelInstance.membersIds shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
