/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HandlerRefreshRes

class HandlerRefreshResTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HandlerRefreshRes
        //val modelInstance = HandlerRefreshRes()

        // to test the property `accessToken`
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

    }
}
