/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.HandlerChatIdResponse

class HandlerChatIdResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of HandlerChatIdResponse
        //val modelInstance = HandlerChatIdResponse()

        // to test the property `chatId`
        should("test chatId") {
            // uncomment below to test the property
            //modelInstance.chatId shouldBe ("TODO")
        }

    }
}
