/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param chatId 
 * @param id 
 * @param senderId 
 * @param sendingTime 
 * @param text 
 * @param userName 
 */


data class CoreMessageInfo (

    @Json(name = "chatId")
    val chatId: kotlin.Int? = null,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "senderId")
    val senderId: kotlin.Int? = null,

    @Json(name = "sendingTime")
    val sendingTime: kotlin.String? = null,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "userName")
    val userName: kotlin.String? = null

) {


}

