/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isDirect 
 * @param membersIds 
 * @param name 
 */


data class HandlerAddChat (

    @Json(name = "is_direct")
    val isDirect: kotlin.Boolean? = null,

    @Json(name = "members_ids")
    val membersIds: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

